library(dplyr)
library(ggplot2)
sales <- data.frame(customer=c(" Aman ","riya","KARAN","Neha","aman","RIYA","Vikas","neha"),region=c("north","South","NORTH","south","North",NA,"WEST","South"),product=c("Laptop","phone","LAPTOP","Tablet","laptop","Phone","tablet","PHONE"),quantity=c(2,5,NA,3,1,4,2,NA),price=c(65000,30000,65000,22000,65000,30000,22000,30000))
sales <- sales |> mutate(customer=tools::toTitleCase(tolower(trimws(customer))),region=tools::toTitleCase(tolower(region)),product=tools::toTitleCase(tolower(product)))
sales$region[is.na(sales$region)] <- "Unknown"
sales$quantity[is.na(sales$quantity)] <- median(sales$quantity,na.rm=TRUE)
sales <- sales |> mutate(revenue=quantity*price)
product_summary <- sales |> group_by(product) |> summarise(total_quantity=sum(quantity),total_revenue=sum(revenue),orders=n()) |> arrange(desc(total_revenue))
region_summary <- sales |> group_by(region) |> summarise(total_revenue=sum(revenue),orders=n()) |> arrange(desc(total_revenue))
print(sales); print(product_summary); print(region_summary)
print(slice_max(product_summary,total_revenue,n=1))
print(slice_max(region_summary,total_revenue,n=1))
ggplot(product_summary,aes(product,total_revenue))+geom_col()+theme_minimal()+labs(title="Revenue by Product")
ggplot(region_summary,aes(region,total_revenue))+geom_col()+theme_minimal()+labs(title="Revenue by Region")
